url: https://richardba.github.io
baseurl:

# Site settings
title: richardba
email: richardtrle@gmail.com
description: "Welcome to my personal github page, my blog and portfolio!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 75C1E3
  secondary: 417199
  secondary-dark: 333

# Team names, titles and social links
people:

- name: Ricardo d'Oliveira
  pic: 1
  position: Analyst, Developer & Technologist

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bitbucket
    url: http://bitbucket.org/richardba
  - title: facebook
    url: http://facebook.com/richardtrle
  - title: github
    url: https://github.com/richardba
  - title: linkedin
    url: https://linkedin.com/in/richardtrle
  - title: twitter
    url: http://twitter.com/richardba

devs:
  - icon: android
  - icon: bitbucket
  - icon: cplusplus
  - icon: gimp
  - icon: git
  - icon: github
  - icon: heroku
  - icon: html5
  - icon: inkscape
  - icon: java
  - icon: javascript
  - icon: jquery
  - icon: linux
  - icon: python
  - icon: ruby
  - icon: mysql
  - icon: postgresql
  - icon: typescript
  - icon: windows8

timeline:
  - number: 1
    period: -2005
    title: High School
    desc: Where everything began, I bet many of you went through that.
  - number: 2
    period: Undergraduate
    title: 2007-2011
    desc: I enrolled in a undergradute course in Computer Science. I always loved computing, things escalated quickly, oh boy look where I'm now. While there were job oportunities, I preferred scientific research, which I still do.
  - number: 3
    period: 2012-2015
    title: System Analysis
    desc: After my college graduation I started working as system analyst, even though I got myself more experienced, I didn't quite enjoy the actual oportunities to work in the private sector. Maybe because I was not as mature as I am now, who nows?
  - number: 4
    period: 2016-2020
    title: MSc. in Computer Science
    desc: My academic and scientific research experience, I enjoyed it at the very little bit. I got myself involved in Computer Graphics research, where World Render was developed. I hope I get engaged into a doctorate soon!
  - number: 5
    period: 2020-
    title: Ready To Take a Flight!
    desc: What future reserves for me?

# Postal address (add as many lines as necessary)
address:
  - line: Avenida Luis Tarquinio, 926
  - line: Salvador, BA 42700-000

form:
  url: uggcf://qbpf.tbbtyr.pbz/sbezf/q/r/1SNVcDYFq7qs4joFwQPNEn487LuX3I4gm6XbbLq6Sqn764SxmVuJIkgN/sbezErfcbafr

# Build settings
markdown: kramdown
permalink: pretty
